# Generated by Django 4.1.7 on 2023-03-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('preco', models.FloatField()),
                ('src', models.ImageField(upload_to='post_img')),
            ],
        ),
    ]
